# Generated by Django 5.2.7 on 2025-10-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('date_of_birth', models.DateField()),
                ('courses', models.ManyToManyField(related_name='students', to='Course.courses')),
            ],
        ),
    ]
