# Generated by Django 5.2.7 on 2025-10-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='_', max_length=50),
            preserve_default=False,
        ),
    ]
